version: '3.3'

services:
  db:
    image: mongo:${MONGO_VER}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VER}
    ports:
      - ${APP_HOST_PORT}:9292/tcp
    networks:
      - front_net

  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VER}
    networks:
      - back_net
      - front_net

  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VER}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
  front_net:
