FROM ruby:2.2-alpine
LABEL name="Otus Reddit ui service"
LABEL version="1.1"
ARG build_deps="make gcc libc-dev"
ENV APP_HOME "/srv/app/"
ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

WORKDIR $APP_HOME
CMD ["puma"]

COPY . $APP_HOME/

# hadolint ignore=DL3018,SC2086
RUN \
  apk --no-cache --update add $build_deps && \
  bundle install && \
  apk del $build_deps
